apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-boot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-spring-boot-app  
  template:
    metadata:
      name: my-spring-boot-app
      labels:
        app: my-spring-boot-app
    spec:
      containers:
      - name: my-spring-boot-app
        image: narasimhaawsdev/my-spring-boot-app:latest
        ports:
        - containerPort: 8080
